# Generated by Django 4.0.3 on 2022-04-11 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='lcoh',
            field=models.TextField(default='0', verbose_name='LCOH'),
        ),
        migrations.AddField(
            model_name='design',
            name='nvp_h2',
            field=models.TextField(default='0', verbose_name='NVP_H2'),
        ),
        migrations.AddField(
            model_name='design',
            name='nvp_h2_output',
            field=models.TextField(default='0', verbose_name='NPV_H2_output'),
        ),
        migrations.AddField(
            model_name='design',
            name='t',
            field=models.TextField(default='0', verbose_name='T'),
        ),
        migrations.AddField(
            model_name='design',
            name='wacc',
            field=models.TextField(default='0', verbose_name='WACC'),
        ),
        migrations.AlterField(
            model_name='design',
            name='develop_cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be on range between 1 and 100'), django.core.validators.MaxValueValidator(limit_value=100, message='Value must be on range between 1 and 100')], verbose_name='Development cost'),
        ),
        migrations.AlterField(
            model_name='design',
            name='elec_size',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be on range between 1 and 10'), django.core.validators.MaxValueValidator(limit_value=10, message='Value must be on range between 1 and 10')], verbose_name='Electrolyzer nominal power'),
        ),
        migrations.AlterField(
            model_name='design',
            name='elec_type',
            field=models.CharField(choices=[('PEM', 'PEM'), ('ALK', 'ALK'), ('SOEC', 'SOEC')], default='PEM', max_length=30, verbose_name='Electrolyzer type'),
        ),
        migrations.AlterField(
            model_name='design',
            name='water_type',
            field=models.CharField(choices=[('Tap', 'Tap Water'), ('demi', 'Deionized-demi Water')], default='tap', max_length=30, verbose_name='Water type'),
        ),
    ]
