# Generated by Django 4.0.3 on 2022-04-21 22:30

import design.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_design_o_s_gen_alter_design_develop_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='o_s_gen',
            field=models.FileField(blank=True, null=True, upload_to=design.models.custom_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'], message='Only csv and xlsx files are allowed')], verbose_name='Input File'),
        ),
    ]
