# Generated by Django 4.0.3 on 2022-04-22 15:04

import design.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_design_o_s_gen_alter_design_develop_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='file_type',
            field=models.CharField(blank=True, choices=[('TMY', 'TMY'), ('TMY_SAM', 'TMY_SAM'), ('TMY_PVsol', 'TMY_PVsol'), ('PVSyst', 'PVSyst')], default='TMY', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='design',
            name='o_s_gen',
            field=models.FileField(blank=True, null=True, upload_to=design.models.custom_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'], message='Only csv and xlsx files are allowed')], verbose_name='Input File'),
        ),
        migrations.AlterField(
            model_name='design',
            name='op_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('On-site', 'User-defined generation vector')], default='PPA', max_length=30, verbose_name='Energy input'),
        ),
        migrations.AlterField(
            model_name='design',
            name='ppa_type',
            field=models.CharField(blank=True, choices=[('24/7', '24/7'), ('Custom', 'Customized')], default='24/7', max_length=30, verbose_name='PPA type'),
        ),
    ]
