# Generated by Django 4.0.3 on 2022-04-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_alter_design_o_s_gen'),
        ('design', '0005_design_file_type_alter_design_o_s_gen_and_more'),
    ]

    operations = [
    ]
