# Generated by Django 4.0.4 on 2022-04-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_merge_20220422_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='nvp_h2',
        ),
        migrations.RemoveField(
            model_name='design',
            name='nvp_h2_output',
        ),
        migrations.RemoveField(
            model_name='design',
            name='t',
        ),
        migrations.RemoveField(
            model_name='design',
            name='wacc',
        ),
        migrations.AddField(
            model_name='design',
            name='curtailed_energy',
            field=models.FloatField(default=0.0, verbose_name='Curtailed energy year 1 [GWh/year]'),
        ),
        migrations.AddField(
            model_name='design',
            name='energy_consumption',
            field=models.FloatField(default=0.0, verbose_name='Energy consumption year 1 [GWh/year]'),
        ),
        migrations.AddField(
            model_name='design',
            name='hydrogen_production',
            field=models.FloatField(default=0.0, verbose_name='Hydrogen production year 1 [tons/year]'),
        ),
        migrations.AddField(
            model_name='design',
            name='oxigen_production',
            field=models.TextField(default='Pronto...', verbose_name='Oxigen production year 1 [tons/year]'),
        ),
        migrations.AddField(
            model_name='design',
            name='present_stack_replacements',
            field=models.FloatField(default=0.0, verbose_name='Present cost of stack replacements [USD]'),
        ),
        migrations.AddField(
            model_name='design',
            name='present_total_cost',
            field=models.FloatField(default=0.0, verbose_name='Present value of total costs [USD]'),
        ),
        migrations.AddField(
            model_name='design',
            name='stack_replacements',
            field=models.IntegerField(default=0, verbose_name='Stack replacements'),
        ),
        migrations.AddField(
            model_name='design',
            name='total_capex',
            field=models.FloatField(default=0.0, verbose_name='Total CAPEX [USD]'),
        ),
        migrations.AddField(
            model_name='design',
            name='water_consumption',
            field=models.FloatField(default=0.0, verbose_name='Water consumption year 1 [m3/year]'),
        ),
        migrations.AddField(
            model_name='design',
            name='year_of_replacements',
            field=models.TextField(default='0', verbose_name='Year of replacements'),
        ),
        migrations.AlterField(
            model_name='design',
            name='lcoh',
            field=models.FloatField(default=0.0, verbose_name='LCOH'),
        ),
    ]
