# Generated by Django 4.0.4 on 2022-05-02 14:04

import design.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_remove_design_nvp_h2_remove_design_nvp_h2_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='debt',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='Debt [%]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='develop_cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Specific Development cost [USD/kW]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='elec_cost',
            field=models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Specific Electrolyzer and BoP cost [USD/kW]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='elec_size',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Electrolyzer nominal power [MW]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='energy_cost',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Energy cost [USD/MWh]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='equity_discount_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='Equity discount rate [%]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='first_category_tax',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='First category Tax [%]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='interest_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='Interest Rate [%]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='nom_power',
            field=models.IntegerField(blank=True, default=10, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='PPA nominal power [MW]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='o_s_gen',
            field=models.FileField(blank=True, null=True, upload_to=design.models.custom_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'], message='Only csv files are allowed')], verbose_name='Input File'),
        ),
        migrations.AlterField(
            model_name='design',
            name='op_type',
            field=models.CharField(choices=[('PPA', 'PPA')], default='PPA', max_length=30, verbose_name='Energy input'),
        ),
        migrations.AlterField(
            model_name='design',
            name='oxigen_production',
            field=models.FloatField(default=0.0, verbose_name='Oxigen production year 1 [tons/year]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='water_cost',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Water cost [USD/m3]'),
        ),
    ]
