# Generated by Django 4.0.4 on 2022-05-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_alter_design_debt_alter_design_develop_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='curtailed_energy',
        ),
        migrations.RemoveField(
            model_name='design',
            name='energy_consumption',
        ),
        migrations.RemoveField(
            model_name='design',
            name='hydrogen_production',
        ),
        migrations.RemoveField(
            model_name='design',
            name='lcoh',
        ),
        migrations.RemoveField(
            model_name='design',
            name='oxigen_production',
        ),
        migrations.RemoveField(
            model_name='design',
            name='present_stack_replacements',
        ),
        migrations.RemoveField(
            model_name='design',
            name='present_total_cost',
        ),
        migrations.RemoveField(
            model_name='design',
            name='stack_replacements',
        ),
        migrations.RemoveField(
            model_name='design',
            name='total_capex',
        ),
        migrations.RemoveField(
            model_name='design',
            name='water_consumption',
        ),
        migrations.RemoveField(
            model_name='design',
            name='year_of_replacements',
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydrogen_production', models.FloatField(default=0.0, verbose_name='Hydrogen production year 1 [tons/year]')),
                ('oxigen_production', models.FloatField(default=0.0, verbose_name='Oxigen production year 1 [tons/year]')),
                ('energy_consumption', models.FloatField(default=0.0, verbose_name='Energy consumption year 1 [GWh/year]')),
                ('curtailed_energy', models.FloatField(default=0.0, verbose_name='Curtailed energy year 1 [GWh/year]')),
                ('water_consumption', models.FloatField(default=0.0, verbose_name='Water consumption year 1 [m3/year]')),
                ('stack_replacements', models.IntegerField(default=0, verbose_name='Stack replacements')),
                ('year_of_replacements', models.TextField(default='0', verbose_name='Year of replacements')),
                ('total_capex', models.FloatField(default=0.0, verbose_name='Total CAPEX [USD]')),
                ('present_stack_replacements', models.FloatField(default=0.0, verbose_name='Present cost of stack replacements [USD]')),
                ('present_total_cost', models.FloatField(default=0.0, verbose_name='Present value of total costs [USD]')),
                ('lcoh', models.FloatField(default=0.0, verbose_name='LCOH')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='design.design')),
            ],
            options={
                'verbose_name': 'result',
                'ordering': ['-created'],
            },
        ),
    ]
