# Generated by Django 4.0.4 on 2022-05-04 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_results_monthly_plot_data_results_yearly_plot_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='debt',
            field=models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='Debt [%]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='equity_discount_rate',
            field=models.FloatField(default=0.12, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='Equity discount rate [%]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='first_category_tax',
            field=models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='First category Tax [%]'),
        ),
        migrations.AlterField(
            model_name='design',
            name='interest_rate',
            field=models.FloatField(default=0.06, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='Interest Rate [%]'),
        ),
    ]
