# Generated by Django 4.0.4 on 2022-05-05 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_alter_design_debt_alter_design_equity_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='elec_cost',
            field=models.FloatField(default=1200, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Specific Electrolyzer and BoP cost [USD/kW]'),
        ),
    ]
