# Generated by Django 4.0.4 on 2022-05-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_alter_design_elec_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='op_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('On-site', 'User-defined generation vector')], default='PPA', max_length=30, verbose_name='Energy input'),
        ),
    ]
