# Generated by Django 4.0.4 on 2022-05-23 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0019_results_h2_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='eff_replacement',
            field=models.FloatField(default=80, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than 0')], verbose_name='Min. electrolyzer efficiency before replacement [%]'),
        ),
        migrations.AddField(
            model_name='design',
            name='sp_footprint',
            field=models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='System footprint [m²/MW]'),
        ),
        migrations.AddField(
            model_name='results',
            name='average_energy_consumption',
            field=models.FloatField(default=0.0, verbose_name='Average energy consumption [kWh/kgH2]'),
        ),
        migrations.AddField(
            model_name='results',
            name='energy_cost',
            field=models.FloatField(default=0.0, verbose_name='Energy cost [USD/year]'),
        ),
        migrations.AddField(
            model_name='results',
            name='energy_plot_data',
            field=models.TextField(blank=True, null=True, verbose_name='energy_plot_data'),
        ),
        migrations.AddField(
            model_name='results',
            name='load_factor',
            field=models.FloatField(default=0.0, verbose_name='Electrolyzer load factor'),
        ),
        migrations.AddField(
            model_name='results',
            name='nvp_energy_cost',
            field=models.FloatField(default=0.0, verbose_name='Present Cost of energy for life cycle [USD]'),
        ),
        migrations.AddField(
            model_name='results',
            name='nvp_land',
            field=models.FloatField(default=0.0, verbose_name='Present Cost of land for life cycle [USD]'),
        ),
        migrations.AddField(
            model_name='results',
            name='nvp_om',
            field=models.FloatField(default=0.0, verbose_name='Present Cost of O&M for life cycle [USD]'),
        ),
        migrations.AddField(
            model_name='results',
            name='nvp_water',
            field=models.FloatField(default=0.0, verbose_name='Present Cost of water for life cycle [USD]'),
        ),
        migrations.AddField(
            model_name='results',
            name='wacc',
            field=models.FloatField(default=0.0, verbose_name='WACC'),
        ),
        migrations.AddField(
            model_name='results',
            name='water_cost',
            field=models.FloatField(default=0.0, verbose_name='Water cost [USD/year]'),
        ),
        migrations.AlterField(
            model_name='results',
            name='curtailed_energy',
            field=models.FloatField(default=0.0, verbose_name='Energy curtailed [GWh/year]'),
        ),
        migrations.AlterField(
            model_name='results',
            name='lcoh',
            field=models.FloatField(default=0.0, verbose_name='LCOH [USD/kgH2]'),
        ),
        migrations.AlterField(
            model_name='results',
            name='present_total_cost',
            field=models.FloatField(default=0.0, verbose_name='Total present cost for life cycle [USD]'),
        ),
        migrations.AlterField(
            model_name='results',
            name='water_consumption',
            field=models.FloatField(default=0.0, verbose_name='Water consumption Y1 [m3/year]'),
        ),
    ]
