# Generated by Django 4.0.4 on 2022-06-02 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_alter_design_land_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='indirect_cost',
            field=models.FloatField(default=1000000, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Indirect costs [USD/project]'),
        ),
        migrations.AddField(
            model_name='design',
            name='installation_cost',
            field=models.FloatField(default=180, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Value must be greater than 1')], verbose_name='Installation cost [USD/kW]'),
        ),
        migrations.AddField(
            model_name='results',
            name='capex_breakdown',
            field=models.TextField(blank=True, null=True, verbose_name='Capex Breakdown data'),
        ),
        migrations.AddField(
            model_name='results',
            name='capex_tot',
            field=models.FloatField(blank=True, null=True, verbose_name='Total capex'),
        ),
        migrations.AddField(
            model_name='results',
            name='opex_breakdown',
            field=models.TextField(blank=True, null=True, verbose_name='Opex Breakdown data'),
        ),
        migrations.AddField(
            model_name='results',
            name='opex_tot',
            field=models.FloatField(blank=True, null=True, verbose_name='Total capex'),
        ),
    ]
