# Generated by Django 4.0.4 on 2022-05-03 21:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Patch Version')),
                ('changes', ckeditor.fields.RichTextField(verbose_name='Change List')),
                ('notes', ckeditor.fields.RichTextField(verbose_name='Notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'version',
                'ordering': ['-version'],
            },
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ['title'], 'verbose_name': 'page'},
        ),
    ]
