# Generated by Django 4.0.4 on 2022-05-03 21:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_patch_alter_pages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
